### ISSUE TITLE
Credit Alyssa X

### ISSUE THREAD

**Issue by TheRedstoneRadiant** [ishaantek/blazex#1]
This extension is clearly a rip of Omni.
It's fine, but you didn't credit the original author which violates the terms of Omni's license.

As stated in the [original](https://github.com/alyssaxuu/omni/blob/master/LICENSE) repository: "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

Please credit the original author by retaining the [license](https://github.com/alyssaxuu/omni/blob/master/LICENSE).

**Comment by ishaantek** [comment]
Hello, I just wanted to test out the code for something, which is why I haven't used the code for my own application. I also do use Alyssa's license for this repository.
